remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

title: Educational Units
description: Provides a single entry point toward self-contained educational units from various domains related to mathematics, computer science and software/systems engineering.
